version: "3.8"

x-base: &base
  image: fastapi_project_template
  entrypoint: ./docker/entrypoint.sh
  depends_on:
    - db
  environment:
    - PROJECT_NAME=Merixstudio FastAPI boilerplate
    - SERVER_NAME=localhost
    - SERVER_HOST=http://localhost:8000
    - POSTGRES_SERVER=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres

services:
  db:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
  backend:
    <<: *base
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: runserver
