apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.app.port | quote }}
      targetPort: {{ .Values.app.port }}
      port: {{ .Values.app.port }}
  selector:
    service: fastapi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: fastapi
  name: fastapi
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      service: fastapi
  template:
    metadata:
      labels:
        service: fastapi
    spec:
      securityContext:
        fsGroup: 101 # fastapi group
      initContainers:
        - args: ["bootstrap"]
          name: bootstrap
          image: {{ .Values.app.image }}
          envFrom:
            - configMapRef:
                name: env
          resources:
            requests:
              memory: "200Mi"
          volumeMounts:
            - mountPath: /app/media
              name: media
      containers:
        - args: ["gunicorn"]
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: env
          image: {{ .Values.app.image }}
          name: fastapi
          ports:
            - containerPort: {{ .Values.app.port }}
          resources:
            requests:
              memory: "200Mi"
          volumeMounts:
            - mountPath: /app/media
              name: media
      restartPolicy: Always
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
      nodeSelector:
        node-type: stateless
      tolerations:
        - key: node-type
          operator: Equal
          value: stateless
          effect: NoSchedule
