apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
          # OR
        - namespaceSelector:
            matchLabels:
              name: kube-system
