apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    service: postgres
spec:
  type: ClusterIP
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    service: postgres

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: postgres
  labels:
    service: postgres
spec:
  selector:
    matchLabels:
      service: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        service: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          resources:
            requests:
              memory: "100Mi"
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
  volumeClaimTemplates:
    - metadata:
        namespace: {{ .Release.Namespace }}
        name: postgres
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard-retain"
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}
