apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.app.media.storage }}
  storageClassName: nfs
